sudo: required
services:
  - docker

before_install:
  - docker build -t dicrescenzoa/ciplayground -f Dockerfile.dev .

script:
  - docker run -e CI=true dicrescenzoa/ciplayground npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "ciplayground"
  env: "ciplayground-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-eu-west-1-060625785112"
  access_key_id:
    secure: "Encrypted <access-key-id>=$AWS_ ACCESS_KEY"
  secret_access_key:
    secure: "Encypted <secret-access-key>=$AWS_SECRET_KEY"